#!/bin/bash

# Get the list of staged files that are Added or Modified
staged_files=$(git diff --cached --name-only --diff-filter=AM)

# Filter for PHP files (configure as you need)
staged_php_files=$(echo "$staged_files" | grep '\.php$')

if [ -n "$staged_php_files" ]; then
  # Run Pint only on the staged files
  if ./vendor/bin/pint --version &>/dev/null; then
    ./vendor/bin/pint --test $staged_php_files >/dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "Code formatting issues found. Please run './vendor/bin/pint' to fix them"
      exit 1
    fi
  else
    echo -e "\e[31m Pre commit error: Laravel Pint installation not found and is required for php code formatting\e[0m"
    exit 1
  fi
fi

exit 0
